version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: finance_tracker_db
    environment:
      POSTGRES_USER: finance_tracker
      POSTGRES_PASSWORD: finance_tracker
      POSTGRES_DB: finance_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: finance_tracker_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
